version: '3.3'
services:
    easyconnect:
        image: hagb/docker-easyconnect:cli # latest, vncless, cli, 7.6.3, vncless-7.6.3, 7.6.7, vncless-7.6.7
        devices:
          - /dev/net/tun
        cap_add: 
          - NET_ADMIN
        volumes:
          - /etc/resolv.conf:/etc/resolv.conf:ro      
          - /opt/easyconnect/easyconn:/root/.easyconn
        environment:
          - EC_VER=7.6.7
          - EXIT=1
        ports:
          - "1080:1080"
